In [7]:
path="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\transaction\\country\\india\\state"

In [8]:
import os
path="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\transaction\\country\\india\\state"
Agg_state_list=os.listdir(path)
Agg_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [9]:
import pandas as pd
import json
import os

path="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\transaction\\country\\india\\state"
Agg_state_list = os.listdir(path)

clm = {'State': [],'Year': [],'Quarter': [],'Transaction_type': [],'Transaction_count': [],'Transaction_amount': []}

for state in Agg_state_list:                                  
    state_path = os.path.join(path, state)
    year_list = os.listdir(state_path)

    for year in year_list:                                   
        year_path = os.path.join(state_path, year)
        quarter_list = os.listdir(year_path)

        for q in quarter_list:                                
            if q.endswith(".json"):
                file_path = os.path.join(year_path, q)
                with open(file_path, "r") as f:
                    data = json.load(f)
          
                    for item in data["data"]["transactionData"]:
                        name = item["name"]
                        count = item["paymentInstruments"][0]["count"]
                        amount = item["paymentInstruments"][0]["amount"]

                        clm['State'].append(state)
                        clm['Year'].append(year)
                        clm['Quarter'].append(int(q.strip(".json")))
                        clm['Transaction_type'].append(name)
                        clm['Transaction_count'].append(count)
                        clm['Transaction_amount'].append(amount)


Agg_Trans= pd.DataFrame(clm)
Agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [10]:
import os
path="C:\\Users\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\insurance\\country\\india\\state"
Agg_state_list=os.listdir(path)
Agg_state_list

<>:2: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
<>:2: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
C:\Users\yadun\AppData\Local\Temp\ipykernel_14820\2133455235.py:2: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
  path="C:\\Users\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\insurance\\country\\india\\state"

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [11]:
import os
import json
import pandas as pd

path="C:\\Users\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\insurance\\country\\india\\state"

clm = {'State': [],'Year': [],'Quarter': [],'insurance_type':[],'insurance_count':[],'insurance_amount':[]}

for state in Agg_state_list:                                     
    state_path = os.path.join(path, state)
    year_list = os.listdir(state_path)

    for year in year_list:                                       
        year_path = os.path.join(state_path, year)
        quarter_list = os.listdir(year_path)

        for q in quarter_list:                                 
            if q.endswith(".json"):
                file_path = os.path.join(year_path, q)
                with open(file_path, "r") as f:
                    data = json.load(f)

                for item in data["data"]["transactionData"]:
                    name=item["name"]
                    count=item["paymentInstruments"][0]["count"]
                    amount=item["paymentInstruments"][0]["amount"]
                    
                    clm['State'].append(state)
                    clm["Year"].append(year)
                    clm["Quarter"].append(int(q.replace(".json","")))
                    clm["insurance_type"].append(name)
                    clm["insurance_count"].append(count)
                    clm["insurance_amount"].append(amount)
Agg_insurance=pd.DataFrame(clm)
Agg_insurance

<>:5: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
<>:5: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
C:\Users\yadun\AppData\Local\Temp\ipykernel_14820\209140876.py:5: SyntaxWarning: "\y" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\y"? A raw string is also an option.
  path="C:\\Users\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\insurance\\country\\india\\state"

,State,Year,Quarter,insurance_type,insurance_count,insurance_amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [12]:
users = data.get("data", {}).get("usersByDevice",[[]])

if users:
    for item in users:
        brand = item.get("brand")
        count = item.get("count")
        percentage = item.get("percentage")
else:
    print("No data found in this file")

AttributeError: 'list' object has no attribute 'get'

In [ ]:
users = data.get("data", {}).get("usersByDevice") or []

for item in users:
    brand = item.get("brand", "Unknown")
    count = item.get("count", 0)
    percentage = item.get("percentage", 0)

    print(brand, count, percentage)

In [ ]:
print(file_path)
print(data)

C:\Users\yadun\OneDrive\Desktop\Abhinand\Project\pulse\data\aggregated\user\country\india\state\andaman-&-nicobar-islands\2022\2.json
{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 80530, 'appOpens': 5180013}, 'usersByDevice': None}, 'responseTimestamp': 1669732284426}

In [ ]:
import os
import json
import pandas as pd
path="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\aggregated\\user\\country\\india\\state"
Agg_state_list=os.listdir(path)

path="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\aggregated\\user\\country\\india\\state"

clm={'State': [],'Year': [],'Quarter': [],'user_type':[],'user_count':[],'user_percentage':[]}

for state in Agg_state_list:                                     
    state_path = os.path.join(path, state)
    year_list = os.listdir(state_path)

    for year in year_list:                                       
        year_path = os.path.join(state_path, year)
        quarter_list = os.listdir(year_path)

        for q in quarter_list:                                 
            if q.endswith(".json"):
                file_path = os.path.join(year_path, q)
                with open(file_path, "r") as f:
                    data = json.load(f)
                
                users = data.get("data", {}).get("usersByDevice") or []
                for item in users:
                    brand = item.get("brand")
                    count = item.get("count")
                    percentage = item.get("percentage")

                
                
                    clm['State'].append(state)
                    clm['Year'].append(year)
                    clm['Quarter'].append(int(q.replace(".json","")))
                    clm['user_type'].append(brand)
                    clm['user_count'].append(count)
                    clm['user_percentage'].append(percentage)

Agg_User=pd.DataFrame(clm)
Agg_User

,State,Year,Quarter,user_type,user_count,user_percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [ ]:
import os
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\vscode\\pulse\\data\\map\\insurance\\hover\\country\\india\\state"
Map_state_list=os.listdir(path)
Map_state_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [ ]:
import json
import pandas as pd
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\map\\insurance\\hover\\country\\india\\state"

clm ={'State': [],'Year': [],'Quarter': [],'District':[],'Insurance_type':[],'Insurance_count':[],'Insurance_amount':[]}

for state in Map_state_list:
    state_path=os.path.join(path,state)
    year_list=os.listdir(state_path)

    for year in year_list:
        year_path=os.path.join(state_path,year)
        quarter_list=os.listdir(year_path)

        for quarter in quarter_list:
            if quarter.endswith(".json"):
                json_file_path=os.path.join(year_path,quarter)
                with open(json_file_path, "r") as f:
                    data = json.load(f)

                    Hover_list=data["data"]["hoverDataList"]
                    for item in Hover_list:
                        Distrct=item["name"]
                        Metric=item["metric"][0]
                        Insr_type=Metric["type"]
                        Insr_count=Metric["count"]
                        Insr_amount=Metric["amount"]

                        clm["State"].append(state)
                        clm["Year"].append(year)
                        clm["Quarter"].append(int(quarter.replace(".json","")))
                        clm["District"].append(Distrct)
                        clm["Insurance_type"].append(Insr_type)
                        clm["Insurance_count"].append(Insr_count)
                        clm["Insurance_amount"].append(Insr_amount)


Map_Insurance=pd.DataFrame(clm)
Map_Insurance

,State,Year,Quarter,District,Insurance_type,Insurance_count,Insurance_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,TOTAL,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,TOTAL,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,TOTAL,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,TOTAL,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,TOTAL,5,1448.0
...,...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,TOTAL,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,TOTAL,4945,7005851.0
13873,west-bengal,2024,4,nadia district,TOTAL,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,TOTAL,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,TOTAL,3559,4439061.0

In [ ]:
import json
import pandas as pd
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\map\\transaction\\hover\\country\\india\\state"

Map_state_list=os.listdir(path)


clm={'State': [],'Year': [],'Quarter': [],'District':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]} 

for state in Map_state_list:
    state_path=os.path.join(path,state)
    year_list=os.listdir(state_path)

    for year in year_list:
        year_path=os.path.join(state_path,year)
        quarter_list=os.listdir(year_path)

        for quarter in quarter_list:
            if quarter.endswith(".json"):
                json_file_path=os.path.join(year_path,quarter)
                with open(json_file_path, "r") as f:
                    data = json.load(f)
                Hover_list=data["data"]["hoverDataList"]
                for item in Hover_list:
                    District=item["name"]
                    Metric=item["metric"][0]
                    T_type=Metric["type"]
                    T_count=Metric["count"]
                    T_amount=Metric["amount"]
                
                clm["State"].append(state)
                clm["Year"].append(year)
                clm["Quarter"].append(int(quarter.replace(".json","")))
                clm["District"].append(Distrct)
                clm["Transaction_type"].append(T_type)
                clm["Transaction_count"].append(T_count)
                clm["Transaction_amount"].append(T_amount)

Map_Transaction=pd.DataFrame(clm)
Map_Transaction

,State,Year,Quarter,District,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,purba medinipur district,TOTAL,528,1.139849e+06
1,andaman-&-nicobar-islands,2018,2,purba medinipur district,TOTAL,1120,3.072437e+06
2,andaman-&-nicobar-islands,2018,3,purba medinipur district,TOTAL,1471,6.387829e+06
3,andaman-&-nicobar-islands,2018,4,purba medinipur district,TOTAL,1485,7.180859e+06
4,andaman-&-nicobar-islands,2019,1,purba medinipur district,TOTAL,1539,7.236060e+06
...,...,...,...,...,...,...,...
1003,west-bengal,2023,4,purba medinipur district,TOTAL,16807885,2.793986e+10
1004,west-bengal,2024,1,purba medinipur district,TOTAL,18129044,2.927784e+10
1005,west-bengal,2024,2,purba medinipur district,TOTAL,22244510,3.404540e+10
1006,west-bengal,2024,3,purba medinipur district,TOTAL,59353613,1.008394e+11
1007,west-bengal,2024,4,purba medinipur district,TOTAL,67833775,1.142771e+11

In [ ]:
import json
import pandas as pd
import os
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\map\\user\\hover\\country\\india\\state"

Map_state_list=os.listdir(path)

clm={'State': [],'Year': [],'Quarter': [],'District':[],'registered_users':[],'app_opens':[]}

for state in Map_state_list:
    state_path=os.path.join(path,state)
    year_list=os.listdir(state_path)

    for year in year_list:
        year_path=os.path.join(state_path,year)
        quarter_list=os.listdir(year_path)

        for quarter in quarter_list:
            if quarter.endswith(".json"):
                
                json_file_path=os.path.join(year_path,quarter)
                
                with open(json_file_path, "r") as f:
                    data = json.load(f)

                hover_list = data.get("data", {}).get("hoverData", {})
                
                for district,value in hover_list.items():
                    
                    user=value.get("registeredUsers")
                    app=value.get("appOpens")
                
                    clm["State"].append(state)
                    clm["Year"].append(year)
                    clm["Quarter"].append(int(quarter.replace(".json","")))
                    clm["District"].append(district)
                    clm["registered_users"].append(user)
                    clm["app_opens"].append(app)



Map_User=pd.DataFrame(clm)

    
Map_User

,State,Year,Quarter,District,registered_users,app_opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [ ]:
import json
import pandas as pd
import os
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\top\\insurance\\country\\india\\state"

Top_state_list=os.listdir(path)


clm={
    'state':[],
    'year':[],
    'quarter':[],
    'Insurance_type':[],
    'Insurance_count':[],
    'Insurance_amount':[],
    'Pincode':[]
}
for state in Top_state_list:
    state_path=os.path.join(path,state)
    if not os.path.isdir(state_path):                      
        continue
    year_list = os.listdir(state_path)

    for year in year_list:
        year_path=os.path.join(state_path,year)
        if not os.path.isdir(year_path):
            continue
        quarter_list=os.listdir(year_path)

        for quarter in quarter_list:
            if quarter.endswith(".json"):
                
                json_file_path=os.path.join(year_path,quarter)
                
                with open(json_file_path, "r") as f:
                    data = json.load(f)
                for z in data["data"].get("district", []):
                    
                    clm['Insurance_type'].append(z["entityName"])
                    clm['Insurance_count'].append(z["metric"]["count"])
                    clm['Insurance_amount'].append(z["metric"]["amount"])
                    clm['Pincode'].append(None)

                    clm['state'].append(state)
                    clm['year'].append(year)
                    clm['quater'].append(int(quarter.replace(".json", "")))

                for z in data["data"].get("pincodes", []):
                    clm['Insurance_type'].append(None)
                    clm['Insurance_count'].append(z["metric"]["count"])
                    clm['Insurance_amount'].append(z["metric"]["amount"])
                    clm['Pincode'].append(z["entityName"])

                    clm['state'].append(state)
                    clm['year'].append(year)
                    clm['quarter'].append(int(quarter.replace(".json", "")))
Top_Insurance=pd.DataFrame(clm)
Top_Insurance

,state,year,quarter,Insurance_type,Insurance_count,Insurance_amount,Pincode
0,andaman-&-nicobar-islands,2020,2,None,3,565.0,744301
1,andaman-&-nicobar-islands,2020,2,None,2,513.0,744104
2,andaman-&-nicobar-islands,2020,2,None,1,282.0,744101
3,andaman-&-nicobar-islands,2020,3,None,9,3432.0,744112
4,andaman-&-nicobar-islands,2020,3,None,7,3948.0,744105
...,...,...,...,...,...,...,...
6663,west-bengal,2024,4,None,713,750354.0,711101
6664,west-bengal,2024,4,None,642,969634.0,700091
6665,west-bengal,2024,4,None,627,761501.0,700150
6666,west-bengal,2024,4,None,619,787836.0,700039
6667,west-bengal,2024,4,None,574,888613.0,700156

In [ ]:
import json
import pandas as pd
import os
path ="C:\\Users\\yadun\\OneDrive\\Desktop\\Abhinand\\Project\\pulse\\data\\top\\user\\country\\india\\state"

Top_state_list=os.listdir(path)


clm={
    'State':[],
    'Year':[],
    'Quarter':[],
    'District':[],
    'Registered_User':[],
    'AppOppened':[],
  
}

for state in Top_state_list:                                     
    state_path = os.path.join(path, state)
    year_list = os.listdir(state_path)

    for year in year_list:                                       
        year_path = os.path.join(state_path, year)
        quarter_list = os.listdir(year_path)

        for q in quarter_list:                                 
            if q.endswith(".json"):
                file_path = os.path.join(year_path, q)
                with open(file_path, "r") as f:
                    data = json.load(f)
                 
                
                district_list = data.get("data", {}).get("districts", [])

                for item in district_list:

                    user = item.get("registeredUsers")
                    app = item.get("appOpens")
                    district = item.get("name")
                
                    clm['State'].append(state)
                    clm['Year'].append(year)
                    clm['Quarter'].append(int(q.replace(".json","")))
                    clm['District'].append(district)
                    clm["Registered_User"].append(user)
                    clm["AppOppened"].append(app)
Top_user=pd.DataFrame(clm)
Top_user.head(100)[]

,State,Year,Quarter,District,Registered_User,AppOppened
0,andaman-&-nicobar-islands,2018,1,south andaman,5846,None
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632,None
2,andaman-&-nicobar-islands,2018,1,nicobars,262,None
3,andaman-&-nicobar-islands,2018,2,south andaman,8143,None
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911,None
...,...,...,...,...,...,...
95,andhra-pradesh,2018,2,east godavari,454398,None
96,andhra-pradesh,2018,2,krishna,431965,None
97,andhra-pradesh,2018,2,guntur,420326,None
98,andhra-pradesh,2018,2,chittoor,414306,None
99,andhra-pradesh,2018,2,anantapur,326383,None

In [ ]:
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:123{Password@1}@localhost:3306/phonepe_analytics")